services:

    #
    # Event listeners
    #
    elcodi.product.category.event_listener.new_category_position:
        class: Elcodi\Admin\ProductBundle\EventListener\NewCategoryPositionEventListener
        tags:
            - { name: doctrine.event_listener, event: preFlush, method: preFlush }

    elcodi.product.category.event_listener.product_has_only_one_category:
        class: Elcodi\Admin\ProductBundle\EventListener\ProductHasOnlyOneCategoryEventListener
        tags:
            - { name: doctrine.event_listener, event: preFlush, method: preFlush, priority: -10 }
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate , priority: -10 }
