services:

    #
    # Services
    #
    elcodi_store.form.location_selector_builder:
        class: Elcodi\Store\GeoBundle\Form\LocationSelectorBuilder
        arguments:
            location_provider: @elcodi.location_provider
