services:

    #
    # Twig extensions
    #
    elcodi_store.twig_extension.encrypt:
        class: Elcodi\Store\CoreBundle\Twig\EncryptExtension
        tags:
            - { name: twig.extension }

    elcodi_store.twig_extension.referrer:
        class: Elcodi\Store\CoreBundle\Twig\ReferrerExtension
        arguments:
            - @elcodi.referrer_provider
        tags:
            - { name: twig.extension }

    elcodi_store.twig_extension.template_locator:
        class: Elcodi\Store\CoreBundle\Twig\TemplateLocatorExtension
        arguments:
            - @service_container
        tags:
            - { name: twig.extension }
