services:

    #
    # Twig extensions
    #
    # Overrides elcodi.twig_extension.language
    #
    elcodi_admin.twig_extension.store_settings:
        class: Elcodi\Admin\LanguageBundle\Twig\LanguageExtension
        decorates: elcodi.twig_extension.language
        arguments:
            - @elcodi.manager.language
            - @elcodi.store_default_language
        tags:
            - { name: twig.extension }
